# Generated by Django 4.1.7 on 2023-04-04 09:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=['top', 'middle'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='images/'),
        ),
    ]
