# Generated by Django 4.1.7 on 2023-04-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='member', on_delete=django.db.models.deletion.PROTECT, to='accounts.role', to_field='slug'),
        ),
    ]
